const ZONES = [
  {
    name: 'Observatorio del Teide', island: 'Tenerife', municipality: 'La Orotava',
    category: 'observatory', subcategory: 'scientific',
    bortle_scale: 1, sqm_estimate: 22.00, seeing_estimate: 0.8, transparency: 9,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 270,
    latitude: 28.30000000, longitude: -16.51666670, altitude: 2390,
    access_type: 'car', accessibility: 'Carretera asfaltada hasta la base. Acceso restringido al recinto científico.',
    has_parking: true, has_bathrooms: true, has_cafe: false, has_mobile_coverage: true,
    has_electricity: true, has_water: true, safety_risk: 2, has_cliffs: false, has_high_wind: true,
    night_access: true, permits_needed: 'Permiso especial para visitas nocturnas al recinto',
    landscape_quality: 5, astro_orientation: 5, photo_composition: 5, photographer_access: 5,
    milky_way_quality: 5, milky_way_season: 'abril-septiembre', deep_sky_quality: 5,
    star_trails_quality: 5, lunar_quality: 5, solar_quality: 5, eclipse_quality: 5,
    description: 'Principal observatorio astronómico de Canarias, gestionado por el IAC. Situado a 2.390 m en el Parque Nacional del Teide. Considerado uno de los mejores cielos del mundo para astronomía profesional.'
  },
  {
    name: 'Observatorio del Roque de los Muchachos', island: 'La Palma', municipality: 'Garafía',
    category: 'observatory', subcategory: 'scientific',
    bortle_scale: 1, sqm_estimate: 22.05, seeing_estimate: 0.7, transparency: 9,
    avg_humidity: 20, avg_cloudiness: 10, clear_nights_per_year: 280,
    latitude: 28.76000000, longitude: -17.88500000, altitude: 2396,
    access_type: 'car', accessibility: 'Carretera asfaltada hasta la cumbre.',
    has_parking: true, has_bathrooms: true, has_cafe: false, has_mobile_coverage: true,
    has_electricity: true, has_water: true, safety_risk: 2, has_cliffs: false, has_high_wind: true,
    night_access: true, permits_needed: 'Permiso para visitas nocturnas',
    landscape_quality: 5, astro_orientation: 5, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'abril-septiembre', deep_sky_quality: 5,
    star_trails_quality: 5, lunar_quality: 5, solar_quality: 5, eclipse_quality: 5,
    description: 'Uno de los observatorios más importantes del mundo, sede del Gran Telescopio Canarias (GTC) de 10.4m. Cielo excepcionalmente oscuro y estable.'
  },
  {
    name: 'Observatorio de Temisas', island: 'Gran Canaria', municipality: 'Agüimes',
    category: 'observatory', subcategory: 'educational',
    bortle_scale: 3, sqm_estimate: 21.50, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 35, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 27.89000000, longitude: -15.41000000, altitude: 800,
    access_type: 'car', accessibility: 'Carretera asfaltada. Acceso público.',
    has_parking: true, has_bathrooms: true, has_cafe: false, has_mobile_coverage: true,
    has_electricity: true, has_water: true, safety_risk: 1,
    night_access: true,
    landscape_quality: 3, astro_orientation: 4, photo_composition: 3, photographer_access: 4,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 3,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 4, eclipse_quality: 3,
    description: 'Observatorio astronómico educativo en el sur de Gran Canaria. Cuenta con telescopios para divulgación y visitas guiadas.'
  },
  {
    name: 'Mirador Astronómico de las Cañadas del Teide', island: 'Tenerife', municipality: 'La Orotava',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.80, seeing_estimate: 1.0, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 265,
    latitude: 28.23333330, longitude: -16.63333330, altitude: 2200,
    access_type: 'car', accessibility: 'Carretera TF-21 asfaltada. Acceso libre.',
    has_parking: true, has_bathrooms: true, has_cafe: true, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 5, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 5, solar_quality: 4, eclipse_quality: 5,
    description: 'Mirador privilegiado dentro del Parque Nacional del Teide. Ofrece vistas espectaculares de la caldera y cielos oscuros excepcionales. Certificado Starlight.'
  },
  {
    name: 'Mirador del Llano del Jable', island: 'La Palma', municipality: 'Villa de Mazo',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.90, seeing_estimate: 1.0, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 12, clear_nights_per_year: 270,
    latitude: 28.60000000, longitude: -17.78333330, altitude: 1500,
    access_type: 'car', accessibility: 'Carretera asfaltada. Acceso libre.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 5, photo_composition: 5, photographer_access: 5,
    milky_way_quality: 5, milky_way_season: 'abril-septiembre', deep_sky_quality: 5,
    star_trails_quality: 5, lunar_quality: 5, solar_quality: 4, eclipse_quality: 5,
    description: 'Mirador astronómico en el sur de La Palma, ideal para la observación del cielo nocturno. Zona de baja contaminación lumínica y excelente transparencia atmosférica.'
  },
  {
    name: 'Pico de las Nieves', island: 'Gran Canaria', municipality: 'Tejeda',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.70, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 30, avg_cloudiness: 18, clear_nights_per_year: 250,
    latitude: 27.96000000, longitude: -15.57000000, altitude: 1949,
    access_type: 'car', accessibility: 'Carretera asfaltada hasta la cumbre.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 4, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Punto más alto de Gran Canaria (1.949m). Vistas panorámicas de la isla y el mar de nubes. Cielo oscuro ideal para astrofotografía de gran angular y time-lapses.'
  },
  {
    name: 'Degollada de la Yegua', island: 'Gran Canaria', municipality: 'San Bartolomé de Tirajana',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 3, sqm_estimate: 21.40, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 27.91000000, longitude: -15.60000000, altitude: 1550,
    access_type: 'car', accessibility: 'Carretera asfaltada. Acceso libre.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true,
    night_access: true,
    landscape_quality: 4, astro_orientation: 5, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 4, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 4, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador astronómico en la cumbre de Gran Canaria. Excelente orientación sur para observar la Vía Láctea. Zona de baja contaminación lumínica.'
  },
  {
    name: 'Mirador de la Corona Forestal', island: 'Tenerife', municipality: 'La Orotava',
    category: 'astronomical_viewpoint', subcategory: 'natural_observatory',
    bortle_scale: 2, sqm_estimate: 21.60, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 250,
    latitude: 28.35000000, longitude: -16.55000000, altitude: 1800,
    access_type: 'car', accessibility: 'Carretera asfaltada. Espacio habilitado.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 4, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 4,
    star_trails_quality: 4, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador en la Corona Forestal de Tenerife, rodeado de pinar canario. Buen acceso y cielos oscuros. Ideal para sesiones de observación nocturna.'
  },
  {
    name: 'Mirador de la Cumbrecita', island: 'La Palma', municipality: 'El Paso',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.80, seeing_estimate: 1.0, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 270,
    latitude: 28.65000000, longitude: -17.85000000, altitude: 1700,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: true, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 5, astro_orientation: 5, photo_composition: 5, photographer_access: 5,
    milky_way_quality: 5, milky_way_season: 'abril-septiembre', deep_sky_quality: 5,
    star_trails_quality: 5, lunar_quality: 5, solar_quality: 4, eclipse_quality: 5,
    description: 'Mirador en la cumbre de La Palma con vistas a la Caldera de Taburiente. Cielo excepcional, considerado Reserva Starlight. Punto de referencia para astroturismo.'
  },
  {
    name: 'Mirador Astronómico de San Pedro', island: 'Tenerife', municipality: 'El Sauzal',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 4, sqm_estimate: 21.00, seeing_estimate: 2.0, transparency: 6,
    avg_humidity: 40, avg_cloudiness: 25, clear_nights_per_year: 200,
    latitude: 28.48000000, longitude: -16.44000000, altitude: 300,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: true, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 3, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 3, milky_way_season: 'mayo-agosto', deep_sky_quality: 2,
    star_trails_quality: 3, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Mirador astronómico en la costa norte de Tenerife, con vistas al océano y al Teide. Buen punto para observación lunar y planetaria.'
  },
  {
    name: 'Mirador de Igualero', island: 'La Gomera', municipality: 'Alajeró',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.70, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 250,
    latitude: 28.08000000, longitude: -17.25000000, altitude: 950,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: false,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 4, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador en el sur de La Gomera con vistas espectaculares a la costa y al océano. Cielo oscuro y baja contaminación lumínica. Ideal para astrofotografía.'
  },
  {
    name: 'Mirador de La Peña', island: 'El Hierro', municipality: 'Valverde',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.80, seeing_estimate: 1.0, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 260,
    latitude: 27.82000000, longitude: -17.96000000, altitude: 650,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 4, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador diseñado por César Manrique en El Hierro. Vistas al océano y al Golfo. Cielo oscuro excelente, ideal para observación astronómica.'
  },
  {
    name: 'Mirador de La Laja', island: 'La Gomera', municipality: 'Hermigua',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 3, sqm_estimate: 21.30, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 35, avg_cloudiness: 25, clear_nights_per_year: 230,
    latitude: 28.15000000, longitude: -17.20000000, altitude: 600,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: false,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 3, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 4, milky_way_season: 'marzo-septiembre', deep_sky_quality: 3,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Mirador en el norte de La Gomera con vistas al valle de Hermigua. Buen punto para observación y fotografía nocturna.'
  },
  {
    name: 'El Pinar', island: 'El Hierro', municipality: 'El Pinar de El Hierro',
    category: 'astronomical_viewpoint', subcategory: 'dark_zone',
    bortle_scale: 2, sqm_estimate: 21.70, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 260,
    latitude: 27.70000000, longitude: -18.00000000, altitude: 800,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 4, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'abril-septiembre', deep_sky_quality: 4,
    star_trails_quality: 4, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Zona del sur de El Hierro con bosque de pino canario. Cielo excepcionalmente oscuro, una de las mejores zonas de Europa para observar estrellas.'
  },
  {
    name: 'Mirador del Guriete', island: 'Gran Canaria', municipality: 'Tejeda',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 3, sqm_estimate: 21.40, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 27.99000000, longitude: -15.59000000, altitude: 1600,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true,
    night_access: true,
    landscape_quality: 4, astro_orientation: 4, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 4,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador en la cumbre de Gran Canaria, cerca de Tejeda. Vistas impresionantes del Roque Nublo y el paisaje volcánico. Cielo oscuro de calidad.'
  },
  {
    name: 'Mirador del Río', island: 'Lanzarote', municipality: 'Haría',
    category: 'landscape_viewpoint', subcategory: 'cliff',
    bortle_scale: 4, sqm_estimate: 21.00, seeing_estimate: 2.0, transparency: 6,
    avg_humidity: 40, avg_cloudiness: 25, clear_nights_per_year: 220,
    latitude: 29.21000000, longitude: -13.48000000, altitude: 400,
    access_type: 'car', accessibility: 'Carretera asfaltada. Obra de César Manrique.',
    has_parking: true, has_bathrooms: true, has_cafe: true, has_mobile_coverage: true,
    has_electricity: true, has_water: true, safety_risk: 2, has_cliffs: true, has_high_wind: true,
    night_access: false,
    landscape_quality: 5, astro_orientation: 2, photo_composition: 5, photographer_access: 3,
    milky_way_quality: 3, milky_way_season: 'mayo-agosto', deep_sky_quality: 2,
    star_trails_quality: 3, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Icónico mirador diseñado por César Manrique en el norte de Lanzarote. Vistas espectaculares del Archipiélago Chinijo y el océano. Principalmente paisajístico.'
  },
  {
    name: 'Montaña de la Corona', island: 'Lanzarote', municipality: 'Haría',
    category: 'astronomical_viewpoint', subcategory: 'volcano',
    bortle_scale: 4, sqm_estimate: 21.10, seeing_estimate: 1.8, transparency: 6,
    avg_humidity: 35, avg_cloudiness: 25, clear_nights_per_year: 220,
    latitude: 29.18000000, longitude: -13.50000000, altitude: 600,
    access_type: 'car', accessibility: 'Carretera asfaltada parcialmente.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 3, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 4, astro_orientation: 3, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 3, milky_way_season: 'mayo-agosto', deep_sky_quality: 2,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Volcán en el norte de Lanzarote, junto al Jameos del Agua. Zona de oscuridad relativa con paisajes volcánicos únicos para fotografía nocturna.'
  },
  {
    name: 'Mirador de Sicasumbre', island: 'Fuerteventura', municipality: 'Pájara',
    category: 'landscape_viewpoint', subcategory: 'coast',
    bortle_scale: 4, sqm_estimate: 21.10, seeing_estimate: 1.8, transparency: 6,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 250,
    latitude: 28.15000000, longitude: -14.22000000, altitude: 300,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 3, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 3, milky_way_season: 'abril-septiembre', deep_sky_quality: 3,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 4, eclipse_quality: 3,
    description: 'Mirador en el sur de Fuerteventura con vistas panorámicas de la costa. Cielo despejado la mayor parte del año. Bueno para astrofotografía de paisaje marino.'
  },
  {
    name: 'Mirador de Morro Velosa', island: 'Fuerteventura', municipality: 'Betancuria',
    category: 'landscape_viewpoint', subcategory: 'coast',
    bortle_scale: 4, sqm_estimate: 21.00, seeing_estimate: 2.0, transparency: 6,
    avg_humidity: 35, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 28.40000000, longitude: -14.05000000, altitude: 650,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: true, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 3, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 3, milky_way_season: 'abril-septiembre', deep_sky_quality: 3,
    star_trails_quality: 3, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Mirador en el centro de Fuerteventura, en el macizo de Betancuria. Vistas de la costa este y oeste. Buen punto para fotografía de paisaje.'
  },
  {
    name: 'Mirador de las Playas', island: 'El Hierro', municipality: 'El Pinar de El Hierro',
    category: 'astronomical_viewpoint', subcategory: 'cliff',
    bortle_scale: 2, sqm_estimate: 21.70, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 25, avg_cloudiness: 15, clear_nights_per_year: 260,
    latitude: 27.63000000, longitude: -17.99000000, altitude: 700,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 3, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 4, photo_composition: 5, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Espectacular mirador en El Hierro con vistas a los acantilados de Las Playas. Cielo oscuro excepcional. Punto privilegiado para astrofotografía nocturna.'
  },
  {
    name: 'Mirador del Palmarejo', island: 'La Gomera', municipality: 'Valle Gran Rey',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 2, sqm_estimate: 21.60, seeing_estimate: 1.2, transparency: 8,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 28.10000000, longitude: -17.32000000, altitude: 700,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: false,
    has_electricity: false, has_water: false, safety_risk: 1,
    night_access: true,
    landscape_quality: 4, astro_orientation: 4, photo_composition: 4, photographer_access: 4,
    milky_way_quality: 5, milky_way_season: 'marzo-octubre', deep_sky_quality: 4,
    star_trails_quality: 4, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'Mirador en el oeste de La Gomera, en el municipio de Valle Gran Rey. Cielo oscuro y vistas panorámicas del valle y el océano. Buen punto de observación.'
  },
  {
    name: 'Mirador de Bandama', island: 'Gran Canaria', municipality: 'Santa Brígida',
    category: 'astronomical_viewpoint', subcategory: 'volcano',
    bortle_scale: 5, sqm_estimate: 20.50, seeing_estimate: 2.5, transparency: 5,
    avg_humidity: 45, avg_cloudiness: 30, clear_nights_per_year: 200,
    latitude: 28.03000000, longitude: -15.45000000, altitude: 500,
    access_type: 'car', accessibility: 'Acceso en coche.',
    has_parking: true, has_bathrooms: false, has_cafe: true, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true,
    night_access: false,
    landscape_quality: 4, astro_orientation: 2, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 2, milky_way_season: 'junio-agosto', deep_sky_quality: 2,
    star_trails_quality: 2, lunar_quality: 3, solar_quality: 3, eclipse_quality: 2,
    description: 'Mirador en el borde de la Caldera de Bandama, un cráter volcánico de 1.000m de diámetro. Vistas espectaculares del interior de la caldera. Principalmente paisajístico diurno.'
  },
  {
    name: 'Mirador del Time', island: 'La Palma', municipality: 'Los Llanos de Aridane',
    category: 'landscape_viewpoint', subcategory: 'cliff',
    bortle_scale: 3, sqm_estimate: 21.20, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 250,
    latitude: 28.66000000, longitude: -17.90000000, altitude: 900,
    access_type: 'car', accessibility: 'Carretera asfaltada.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 2, has_cliffs: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 3, photo_composition: 4, photographer_access: 3,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 3,
    star_trails_quality: 4, lunar_quality: 3, solar_quality: 3, eclipse_quality: 3,
    description: 'Mirador en la costa oeste de La Palma con vistas al valle de Aridane y al océano. Posición privilegiada para observar la puesta de sol y cielos nocturnos.'
  },
  {
    name: 'Roque Nublo', island: 'Gran Canaria', municipality: 'Tejeda',
    category: 'astronomical_viewpoint', subcategory: 'starlight',
    bortle_scale: 3, sqm_estimate: 21.40, seeing_estimate: 1.5, transparency: 7,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 240,
    latitude: 27.97000000, longitude: -15.61000000, altitude: 1700,
    access_type: 'hike', accessibility: 'Sendero de 1.5 km desde la Degollada de la Yegua.',
    has_parking: true, has_bathrooms: false, has_cafe: false, has_mobile_coverage: true,
    has_electricity: false, has_water: false, safety_risk: 3, has_cliffs: true, has_high_wind: true,
    night_access: true,
    landscape_quality: 5, astro_orientation: 4, photo_composition: 5, photographer_access: 3,
    milky_way_quality: 4, milky_way_season: 'abril-septiembre', deep_sky_quality: 4,
    star_trails_quality: 5, lunar_quality: 4, solar_quality: 3, eclipse_quality: 4,
    description: 'El Roque Nublo (1.813m) es el monumento natural más emblemático de Gran Canaria. Senda nocturna popular para astrofotografía con el roque como elemento compositivo.'
  },
  {
    name: 'Parque Nacional de Timanfaya', island: 'Lanzarote', municipality: 'Yaiza',
    category: 'landscape_viewpoint', subcategory: 'volcano',
    bortle_scale: 4, sqm_estimate: 21.00, seeing_estimate: 1.8, transparency: 6,
    avg_humidity: 30, avg_cloudiness: 20, clear_nights_per_year: 250,
    latitude: 29.00000000, longitude: -13.75000000, altitude: 300,
    access_type: 'car', accessibility: 'Acceso en coche con visitas guiadas. No se permite acceso nocturno independiente.',
    has_parking: true, has_bathrooms: true, has_cafe: true, has_mobile_coverage: true,
    has_electricity: true, has_water: true, safety_risk: 3, has_cliffs: false, has_high_wind: true,
    night_access: false,
    landscape_quality: 5, astro_orientation: 3, photo_composition: 5, photographer_access: 2,
    milky_way_quality: 3, milky_way_season: 'mayo-agosto', deep_sky_quality: 2,
    star_trails_quality: 3, lunar_quality: 3, solar_quality: 4, eclipse_quality: 3,
    description: 'Parque Nacional de Timanfaya, paisaje volcánico único. Las Montañas del Fuego ofrecen un escenario extraordinario. Acceso nocturno restringido a actividades autorizadas.'
  }
];

export default ZONES;
